In [3]:
import numpy as np
matrix = np.array([
                    [5,10,15],
                    [20,25,30],
                    [35,40,45]
                  ])

In [8]:
print(matrix[1:2,0:2])

[[20 25]]


In [9]:
vector = np.array([5,10,15,20])
vector ==10

array([False,  True, False, False], dtype=bool)

In [10]:
matrix==25

array([[False, False, False],
       [False,  True, False],
       [False, False, False]], dtype=bool)

In [11]:
p = np.array(["1","2","3"])
print(p)

['1' '2' '3']


In [12]:
p = p.astype(float)
print(p)

[ 1.  2.  3.]


In [13]:
p.min()

1.0

In [14]:
matrix.sum(axis=1)

array([ 30,  75, 120])

In [16]:
matrix.shape

(3, 3)

In [22]:
np.ones((3,4,5),dtype=np.int32)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [31]:
np.random.random((2,3))

array([[ 0.36669698,  0.21016958,  0.60251016],
       [ 0.53813905,  0.75442137,  0.79572494]])

In [29]:
from numpy import pi
np.linspace(0, 2*pi,5)

array([ 0.        ,  1.57079633,  3.14159265,  4.71238898,  6.28318531])

In [44]:
data = np.sin(np.arange(20)).reshape(5,4)
print(data)
ind = data.argmax(axis=0)
print(ind)
data_max= data[ind,range(data.shape[1])]
print(data_max)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]
[ 0.98935825  0.84147098  0.99060736  0.6569866 ]


In [45]:
a = np.arange(0, 40, 10)
print(a)
b = np.tile(a,(4,3))
print(b)

[ 0 10 20 30]
[[ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]
 [ 0 10 20 30  0 10 20 30  0 10 20 30]]


In [60]:
a= np.array([[4,3,5],[1,2,1]])
x= np.array([1,4,2,5,6])
print(a)
print("________")
b = np.sort(a,axis=1)
print(b)
a.sort(axis=1)
print(a)
print("_________")
a = np.array([4,3,1,2])
j = np.argsort(a)
print(j)
print(a[j])

[[4 3 5]
 [1 2 1]]
________
[[3 4 5]
 [1 1 2]]
[[3 4 5]
 [1 1 2]]
_________
[2 3 1 0]
[1 2 3 4]
